version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:14.8
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=passdb
      - POSTGRES_DB=database
  redis:
    image: redis:6.2.12-alpine
volumes:
  postgres_data: