name: Django CI

on:
  push:
    branches: [ "main" , "django4_tenants_users"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14.8
        # Provide the password for postgres
        env:
          POSTGRES_USER: userdb
          POSTGRES_PASSWORD: passworddb
          POSTGRES_DB: database
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6.2.12-alpine
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup .env file
      run: |
        cp .env.example .env
    - name: Run Tests
      run: |
        python manage.py test
